---
- name: Add the ondrej PHP PPA
  apt_repository: repo='ppa:ondrej/php'
- name: Update the apt cache
  apt: update_cache=yes cache_valid_time=3600
- name: Install required tools
  apt: name={{item}}
  with_items:
    - unzip
- name: Install PHP
  apt: name={{item}} state=installed
  with_items:
    - php
    - php-fpm
    - php-mysql
    - php-xml
- name: Remove Apache2 (installed by php)
  apt: name=apache2 state=removed
