---
- name: View AWS machines
  hosts: all
  connection: local
  gather_facts: False
  tasks:
  - ec2_remote_facts:
      region: eu-west-1
      filters:
        "instance-state-name": running
        "tag:project": AnsibleScaling
    register: instance_list
  - debug: var=instance_list
