#!/usr/bin/python

from ansible.module_utils.basic import *
import xmlrpclib

def main():
    module = AnsibleModule(
        argument_spec={
            "url": {"required": True},
            "username": {"aliases": ["name"], "required": True},
            "password": {"required": True},
            "display_name": {"required": False}
        }
    )
    params = module.params
    server = xmlrpclib.ServerProxy("%s/xmlrpc.php" % params["url"],
                                   use_datetime=True)
    res = server.demo.sayHello()
    module.exit_json(changed=True, name=res)

if __name__ == "__main__":
    main()
