#!/usr/bin/python

from ansible.module_utils.basic import *

def main():
    module = AnsibleModule(
        argument_spec={
            "url": {"required": True},
            "username": {"aliases": ["name"], "required": True},
            "password": {"required": True},
            "display_name": {"required": False}
        }
    )
    params = module.params
    module.exit_json(changed=True, name=params["name"])

if __name__ == "__main__":
    main()
